"""
Embedding utilities for ticket similarity search

This module provides functions to load and search ticket embeddings
generated by the generate_ticket_embeddings.py utility script.
"""

import json
import math
from pathlib import Path
from typing import List, Dict, Any, Optional, Tuple
from dataclasses import dataclass

@dataclass
class TicketEmbedding:
    """Represents a ticket embedding with metadata"""
    ticket_id: str
    content_hash: str
    embedding: List[float]
    content_preview: str
    generated_at: str
    token_count: int

@dataclass
class SimilarityResult:
    """Represents a similarity search result"""
    ticket_id: str
    similarity: float
    content_preview: str
    
    def __str__(self):
        return f"{self.ticket_id} (similarity: {self.similarity:.4f})"

class EmbeddingManager:
    """Manages ticket embeddings for similarity search"""
    
    def __init__(self, embeddings_file: str = "data/ticket_embeddings.json"):
        """
        Initialize the embedding manager
        
        Args:
            embeddings_file: Path to the embeddings JSON file
        """
        self.embeddings_file = Path(embeddings_file)
        self.embeddings: Dict[str, TicketEmbedding] = {}
        self.metadata: Dict[str, Any] = {}
        self._load_embeddings()
    
    def _load_embeddings(self) -> None:
        """Load embeddings from file"""
        if not self.embeddings_file.exists():
            print(f"⚠️  Embeddings file not found: {self.embeddings_file}")
            print("   Run 'python generate_ticket_embeddings.py' to generate embeddings")
            return
        
        try:
            with open(self.embeddings_file, 'r', encoding='utf-8') as f:
                data = json.load(f)
            
            self.metadata = data.get("metadata", {})
            
            # Load embeddings into dataclass objects
            for embedding_data in data.get("embeddings", []):
                ticket_embedding = TicketEmbedding(
                    ticket_id=embedding_data["ticket_id"],
                    content_hash=embedding_data["content_hash"],
                    embedding=embedding_data["embedding"],
                    content_preview=embedding_data["content_preview"],
                    generated_at=embedding_data["generated_at"],
                    token_count=embedding_data["token_count"]
                )
                self.embeddings[ticket_embedding.ticket_id] = ticket_embedding
                
        except Exception as e:
            print(f"❌ Error loading embeddings: {e}")
    
    def cosine_similarity(self, vec1: List[float], vec2: List[float]) -> float:
        """
        Calculate cosine similarity between two vectors
        
        Args:
            vec1: First vector
            vec2: Second vector
            
        Returns:
            Similarity score between -1 and 1 (1 = identical, 0 = orthogonal, -1 = opposite)
        """
        if len(vec1) != len(vec2):
            raise ValueError(f"Vector dimensions don't match: {len(vec1)} vs {len(vec2)}")
        
        # Calculate dot product
        dot_product = sum(a * b for a, b in zip(vec1, vec2))
        
        # Calculate magnitudes
        magnitude1 = math.sqrt(sum(a * a for a in vec1))
        magnitude2 = math.sqrt(sum(a * a for a in vec2))
        
        # Avoid division by zero
        if magnitude1 == 0 or magnitude2 == 0:
            return 0.0
        
        return dot_product / (magnitude1 * magnitude2)
    
    def find_similar_tickets(
        self, 
        query_embedding: List[float], 
        top_k: int = 5,
        min_similarity: float = 0.0
    ) -> List[SimilarityResult]:
        """
        Find tickets similar to a query embedding
        
        Args:
            query_embedding: The embedding vector to search for
            top_k: Maximum number of results to return
            min_similarity: Minimum similarity threshold (0.0 to 1.0)
            
        Returns:
            List of similarity results, sorted by similarity (highest first)
        """
        if not self.embeddings:
            return []
        
        similarities = []
        
        for ticket_id, ticket_embedding in self.embeddings.items():
            similarity = self.cosine_similarity(query_embedding, ticket_embedding.embedding)
            
            if similarity >= min_similarity:
                similarities.append(SimilarityResult(
                    ticket_id=ticket_id,
                    similarity=similarity,
                    content_preview=ticket_embedding.content_preview
                ))
        
        # Sort by similarity (highest first) and return top_k
        similarities.sort(key=lambda x: x.similarity, reverse=True)
        return similarities[:top_k]
    
    def find_similar_to_ticket(
        self, 
        ticket_id: str, 
        top_k: int = 5,
        min_similarity: float = 0.0
    ) -> List[SimilarityResult]:
        """
        Find tickets similar to an existing ticket
        
        Args:
            ticket_id: ID of the ticket to find similarities for
            top_k: Maximum number of results to return
            min_similarity: Minimum similarity threshold (0.0 to 1.0)
            
        Returns:
            List of similarity results, excluding the query ticket itself
        """
        if ticket_id not in self.embeddings:
            print(f"⚠️  Ticket {ticket_id} not found in embeddings")
            return []
        
        query_embedding = self.embeddings[ticket_id].embedding
        results = self.find_similar_tickets(query_embedding, top_k + 1, min_similarity)
        
        # Remove the query ticket itself from results
        return [result for result in results if result.ticket_id != ticket_id][:top_k]
    
    def get_embedding_info(self) -> Dict[str, Any]:
        """
        Get information about loaded embeddings
        
        Returns:
            Dictionary with embedding metadata and statistics
        """
        return {
            "total_embeddings": len(self.embeddings),
            "model": self.metadata.get("model", "unknown"),
            "dimension": self.metadata.get("dimension", 0),
            "generated_at": self.metadata.get("generated_at", "unknown"),
            "processing_stats": self.metadata.get("processing_stats", {}),
            "available_tickets": list(self.embeddings.keys())
        }
    
    def has_ticket(self, ticket_id: str) -> bool:
        """Check if a ticket has an embedding"""
        return ticket_id in self.embeddings
    
    def get_ticket_embedding(self, ticket_id: str) -> Optional[TicketEmbedding]:
        """Get the embedding for a specific ticket"""
        return self.embeddings.get(ticket_id)

# Convenience functions for easy import and use

def load_embeddings(embeddings_file: str = "data/ticket_embeddings.json") -> EmbeddingManager:
    """
    Load embeddings and return an EmbeddingManager instance
    
    Args:
        embeddings_file: Path to the embeddings JSON file
        
    Returns:
        EmbeddingManager instance
    """
    return EmbeddingManager(embeddings_file)

def find_similar_tickets(
    query_embedding: List[float], 
    top_k: int = 5,
    embeddings_file: str = "data/ticket_embeddings.json"
) -> List[SimilarityResult]:
    """
    Convenience function to find similar tickets
    
    Args:
        query_embedding: The embedding vector to search for
        top_k: Maximum number of results to return
        embeddings_file: Path to the embeddings JSON file
        
    Returns:
        List of similarity results
    """
    manager = EmbeddingManager(embeddings_file)
    return manager.find_similar_tickets(query_embedding, top_k)

# Example usage functions for testing

def demo_similarity_search():
    """Demo function showing how to use the embedding system"""
    print("🔍 Embedding Similarity Search Demo")
    print("=" * 50)
    
    # Load embeddings
    manager = load_embeddings()
    info = manager.get_embedding_info()
    
    print(f"📊 Loaded {info['total_embeddings']} embeddings")
    print(f"🤖 Model: {info['model']}")
    print(f"📏 Dimensions: {info['dimension']}")
    print()
    
    # Show available tickets
    print("🎫 Available tickets:")
    for ticket_id in info['available_tickets']:
        embedding = manager.get_ticket_embedding(ticket_id)
        print(f"   {ticket_id}: {embedding.content_preview}")
    print()
    
    # Find tickets similar to each ticket
    for ticket_id in info['available_tickets']:
        print(f"🔍 Tickets similar to {ticket_id}:")
        similar = manager.find_similar_to_ticket(ticket_id, top_k=3, min_similarity=0.1)
        
        if similar:
            for result in similar:
                print(f"   • {result}")
        else:
            print("   • No similar tickets found")
        print()

if __name__ == "__main__":
    demo_similarity_search()
